### PR TITLE
Fixes #43: Initialize canvas size when running benchmarks directly

### LINKED ISSUE #43: Tests ran via the "link" feature have incorrect stage width & height
When running tests via the links generated in developer mode, the Stage element's width & height are too small. This makes running from URLs, e.g. for automated testing, behave differently than running the benchmark.

Example URL:
https://browserbench.org/MotionMark/developer.html?warmup-length=2000&warmup-frame-count=30&first-frame-minimum-length=0&test-interval=30&display=minimal&tiles=big&controller=fixed&system-frame-rate=60&frame-rate=60&time-measurement=performance&suite-name=MotionMark&test-name=CanvasArcs&complexity=1000

Example output:
image

### PR DESCRIPTION
**Pull request by vmiura**

### CODE REVIEW

File: MotionMark/resources/debug-runner/debug-runner.js [hunk 1]
```diff
@@ -688,6 +688,7 @@ Utilities.extendObject(window.benchmarkController, {
             return false;
 
         setTimeout(function() {
+            benchmarkController.determineCanvasSize();
```
Comment (smfr) [inline MotionMark/resources/debug-runner/debug-runner.js:691]: I would move this out of the timeout callback, so that `startBenchmarkImmediatelyIfEncoded` looks more like `startBenchmark`.

Comment (vmiura) [reply MotionMark/resources/debug-runner/debug-runner.js]: Updated below. PTAL.

**Review by smfr — APPROVED** [review]
